# Generated by Django 2.2.3 on 2022-04-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Menssagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menssagem', models.TextField()),
                ('edital', models.ForeignKey(default='sem menção', on_delete=django.db.models.deletion.DO_NOTHING, to='editais_ifma.Edital')),
            ],
        ),
    ]
