# Generated by Django 2.2.3 on 2022-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais_ifma', '0003_auto_20220426_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='menssagens',
            name='usuario',
            field=models.CharField(default='Anônimo', max_length=45),
        ),
    ]
