# Generated by Django 2.2.3 on 2022-04-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editais_ifma', '0004_menssagens_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menssagens',
            name='edital',
            field=models.ForeignKey(blank=True, default='sem mensão', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='editais_ifma.Edital'),
        ),
    ]
