# Generated by Django 2.2.3 on 2022-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais_ifma', '0007_auto_20220426_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menssagens',
            name='usuario',
            field=models.CharField(default='Anônimo', max_length=15),
        ),
    ]
